### PR TITLE
build node.js extensions with an 'init' symbol

### PR DESCRIPTION
**Pull request by johncant**
Hi guys,

thanks to @oliver---- 's gist and his code, I got my header to SWIGify then compile, but only after adding the 'init' function which the node runtime looks for.

I also added two macros, which seem to make sense given equivalent macros for other languages - are they right?

### CODE REVIEW

**Comment by johncant** [comment]
There's no way I would have understood it without your efforts.

**Comment by obuchtala** [comment]
Find an 'in-production' node module here
     https://github.com/substance/store

I fixed some stuff lately... and this is really working.
(including npm setup)

**Comment by obuchtala** [comment]
```
%module redis

%header %{
#define SWIG 1

#include <jsobjects_v8.hpp>
#include <redis_error.hpp>
#include <redis_access.hpp>

using namespace jsobjects;
%}

%include <std_string.i>
%include <node.i>

%include <jsobjects.i>

/* important: declare all methods which create new instances here */
%newobject RedisAccess::Create;
%newobject RedisAccess::asList;
%newobject RedisAccess::asHash;

%include "redis_error.hpp"
%include "redis_access.hpp"

%node(redis)
```

Notes:
- jsobjects: https://github.com/oliver----/jsobjects
  allows bi-directional usage of javascript objects... will be integrated into the swig module soon
- `<node.i>`: includes everything necessary for node build
- %node(...): use same name as the module

Have a look at this and provide feedback :)

**Comment by johncant** [comment]
You're right. I built my node module with node-waf, which is deprecated. DUH!

**Pull request closed without merging**
