### PR TITLE
Enhanced V8 Support

### PR DESCRIPTION
**Pull request by lefticus**
I've been updating SWIG-V8 to fully support building of V8 bindings for [OpenStudio](http://openstudio.nrel.gov/). OpenStudio is a very large (approximately 26,000 wrapped functions across 34 SWIG modules) project which currently supports Ruby and C# via SWIG.

Changes include
- Full support of building Node modules (partially pulled from another fork of your code)
- Support of the latest version of V8. This led to some conditionally compiled code I don't love, but it seemed necessary. The issue is due to many functions being deprecated by V8
- Support for modules to reference and use previously loaded modules by storing the swig state in the global V8 state object
- Fixes of multiple overloaded functions with the same name but in different classes
- Fix returning of const std::string & objects
- Fix incorrect include in std_pair.i
- Fix inheritance of base classes defined in previous modules.
- Add support for %begin section

There is still one known issue. There seems to be a problem with:

``` javascript
someFunctionExpectingBaseObject(derivedObject);
```

The problem only seems to occur if BaseClass is defined in a separate SWIG generated module.

Also, I'm quite sure that the unit test suite defined in SWIG needs to be updated.

-Jason

### CODE REVIEW

**Comment by lefticus** [comment]
I fixed the last remaining type checking issue for inheritance that I was aware of in d1601f1

**Comment by obuchtala** [comment]
Hi Jason,

sounds promising!
I will have a closer look at it the next days and pull in the changes.

Thanks!

Cheers,
Oliver

2013/3/23 Jason Turner notifications@github.com

**Comment by lefticus** [comment]
The main concern I have is with the #ifdefs around Node.js modules vs pure V8. If you can think of a better way to address this, let me know.

-Jason

**Comment by lefticus** [comment]
I was curious if you've had a chance to look at this yet. We've been using it quite successfully now for a while.

**Comment by lefticus** [comment]
@whoozle and @ewmailing I saw your respective forks in the network and thought I should call your attention to this merge request. I've implemented complete (and switchable) Node.js and V8 support, as well as already having fixed all known crashes and type-emitting bugs. As the description for the pull request states, this fork currently works for wrapping OpenStudio, which is an extremely large multi-module project.

I think we've already duplicated work, but it'd be great if we could collaborate to see which bugs one of us has fixed and the others have missed and get all of this work merged back into SWIG.

**Comment by ewmailing** [comment]
Thank you Jason for reaching out. Yes, I totally want to collaborate.

I glanced over your commit messages, and I don't think there is much
overlap. Most of my bug fixes have been memory leak related. I have
been testing mostly the pure C side of things because I have a long
list of things I need to get bound and to get confidence with the SWIG
generators, I wanted to start simpler.

I am doing application embedding and need to support both v8 and
JSCore. I noticed that both backends had similar bugs. So an relevant
bugs you fixed in v8, I would love to see audited in JSCore too.

Your node.js stuff module loading stuff might be interesting to me,
though I don't know enough yet. The environment I'm in has
reimplemented something that behaves like (conforms to?) the commonjs
'require' system for modules. My current problem with SWIG for
Javascript is that it puts all my bound stuff into a global variable
instead of returning it as a return value for something like require.
I don't actually understand enough of how all this works yet, but I
can't help wondering if your patches on this may work to solve my
problem.

Thanks,

## Eric

Beginning iPhone Games Development
http://playcontrol.net/iphonegamebook/

**Comment by whoozle** [comment]
:+1: Great, I will check if your v8 implementation works with my project and switch to it, if it does. I could check your stuff on monday or if I'd be too busy in business trip, will check as I return back to office. Maybe in the middle of the next week or something. Anyway, my changes are mostly hackish, just making original code work with recent v8, so I think no merging will be required.

@ewmailing, you could call _your-module__initialize function with any v8::Object, not only global object from v8::Context, if I understood your problem right. Try wrap initialize with something like below:

```
v8::Handle<v8::Object> RequireMyModule() {
  v8::HandleScope scope;
  v8::Handle<v8::Object> module(v8::Object::New());
  my_module_initialize(module); //swig-generated wrapper
  return scope.Close(module);
}
```

**Comment by lefticus** [comment]
I will look at the changes from both of you and see about merging them into my branch, since mine has the most significant changes overall.

My main concern is that I've already 2x updated the code to work with the latest V8 API. There's no API version number, so know way to know which one we are building against. Also, the V8 API changes so quickly, I feel like it will be impossible to ever properly support it. But I'll merge in your changes which at least get it up to the most current rev. Unless I've lost track this is already 3 sets of deprecated API's in the 5 months I've been working on this project.

**Comment by ewmailing** [comment]
Ooops. I'm still tied to the version of v8 that SWIG originally works
with. For various reasons outside my control, I don't have the ability
to upgrade to the latest v8 right now. So I really need some logic in
the SWIG generators that can deal with the different v8 versions.

Thanks,
Eric

**Comment by lefticus** [comment]
I did find that there actually are version numbers for V8, however, they are hidden in the .cpp files, so there is no way to know at compile time which API we are compiling against. 

Does anyone have any suggestions for how to address this problem of the quickly changing V8 API?

**Comment by ewmailing** [comment]
How about we use #ifdefs in the SWIG generated output and introduce a
set of our own #defines to trigger the correct blocks to be compiled.
These #defines could be specified through via the compiler (-D flags),
or perhaps a swig command line switch to write in the code path being
taken.

I suspect for the moment, there are only two groups of users...those
using the old version that SWIG was originally written for, and the
latest which you fixed. Maybe we can rely on that to simplify the
problem for now.

Thanks,
Eric

**Comment by whoozle** [comment]
@lefticus I added your branch as an upstream remote in git, and merged all your changes. What would you suggest to do next? I think most of my changes tied with newer v8 api. (v8::Persistent will be uncopyable/unassignable and wont cast to handle by default). Also, I fixed template handle life-time issues, I believe, this causes my embedded hardware to crash frequently (might be unreproducible on machine with lot of ram)

**Comment by lefticus** [comment]
@whoozle It looks clean. I'm going to try and merge yours back into my branch and make sure it works for what I need. Then I'll address @ewmailing questions about supporting older versions as well. I think that the "old version" support can be properly addressed by the NODE compile flag I currently have in my branch.

**Comment by lefticus** [comment]
@whoozle I merged in your changes, and had to make a couple of adjustments.

Almost as if on queue, V8 deprecated an API you were using on the 3.19 branch, in their effort to rewrite the v8::Persistent API.

Also, I had to roll back some of the changes you made in the `#ifdef BUILDING_NODE_MODULE` sections because the V8 API's you wanted to use there simply do not exist in the version of V8 shipping with Node.js yet.

Also, regarding @ewmailing concerns, I think that if we make those to read "`BUILDING_NODE_MODULE || V8_3_14`" we'll be able to get combined support for older versions of V8.

I still need to review the changes @ewmailing made to see what needs to be pulled in as well.

-Jason

**Comment by ewmailing** [comment]
> I still need to review the changes @ewmailing made to see what needs to be
> pulled in as well.
> 
> -Jason

Let me know if you need me to explain anything in my changes. (I think
there was a test case/example written in the comments on the main leak
I was trying to fix.)

@everybody: Has anybody worked on typemaps? One of the things I'm
trying to bind needs multiple return values (OUTPUT*) and the ability
to pass arrays of objects.

Thanks,
Eric

**Comment by whoozle** [comment]
@everybody ops. I believe typemaps had been working somewhere in the past. Today we found that typemap(out) does not work too. I will checkout pre-merge version and if it works I will bisect tomorrow.

**Comment by whoozle** [comment]
@everybody sorry, I must have missed something. swig searches 'out' typemaps of type 'MY_TYPE *', so this confused me. Everything works fine. Sorry. :) Thanks for your great work, @lefticus! :+1:

**Comment by ewmailing** [comment]
> Also, regarding @ewmailing concerns, I think that if we make those to read
> "`BUILDING_NODE_MODULE || V8_3_14`" we'll be able to get combined support
> for older versions of V8.

I started trying you changes (haven't merged yet). Can you clarify the
usage case of BUILDING_NODE_MODULE. I've found that in order for my
existing (original swig/v8) stuff to compile, I have to #define
BUILDING_NODE_MODULE. Is that the intended behavior? I am not using
Node, but a separate environment that has embedded v8 for application
use.

Also, <module>_initialize signature is wrong in the legacy case. I
need the single parameter version:
void example_initialize(v8::Handlev8::Object global_obj)
(Maybe I can adapt, but I haven't figured out what the second parameter is.)

But the very last line in the function won't work in my case since I
don't actually have Node.
NODE_MODULE(example, example_initialize);

Also, the use of assert() in the code requires a #include <assert.h>.

Finally, is there an easy way to add command line switches to swig to
generate the appropriate #defines like in the code?
 #define BUILDING_NODE_MODULE

Still playing with things...

Thanks,
Eric

**Comment by ewmailing** [comment]
@everybody: I merged with the @whoozle branch which I believed had
already merged everything else. So please review my branch to make
sure everything is reasonable.

**Comment by whoozle** [comment]
@ewmailing have you seen my two last commits? d55870cb and 0563b57f? the first one needs review from @lefticus  I think

**Comment by lefticus** [comment]
@whoozle This all looks great. I'll pull your changes in and double check them against the code I need to support. Work has had me distracted for the past week.

**Comment by lefticus** [comment]
@ewmailing @whoozle this is working well still for OpenStudio and supporting all of the functionality I need. It seems all of the patches have been merged into one place and we have switchable support for 'old' V8 (which also supports Node.js's version of V8) and the latest released version of V8.

@oliver---- What do we need to do from here to get this merged into mainline SWIG and into the next release?

**Comment by lefticus** [comment]
@wsfulton what are the next steps for getting this work pulled back in towards the mainline SWIG?

**Comment by wsfulton** [comment]
I'd love to see javascript merged into mainline and can help do this. I will review the code after you have the following:
- Documentation that isn't embarrassing - Doc/Manual/Javascript.html needs some updating.
- Examples and test-suite passing. Please configure Travis (the top level .travis.yml file) to run the examples and test-suite like the other languages (in mainline master). You probably want to get this working in your github repo - enabling Travis is easy.

Once this is done, I'd like to see a pull request against mainline master. The pull request will report the Travis results including your pull request and will allow me to review and comment. Any questions, please ask on the swig-devel mailing list or on github.

**Comment by obuchtala** [comment]
Hi,

sorry for being off so long.
I take a round to review all things that happened in the meantime.

cheers,
Oliver

**Comment by obuchtala** [comment]
Hi all,

please reset (--hard) your branches, and rebase your latest changes, onto c291675ccef1b058ea5e4c642f0f5b2e72b9e006

which is a rebased version of all your work.
I.e., this version is based on top of a commit which is part of the swig main repository index.

Cheers,
Oliver

**Comment by obuchtala** [comment]
@wsfulton hmmm yes.. documentation is rather embarrassing... I will rewrite it.
Another thing: directors are not yet implemented. However, on the way there I had developed a header only library which does 90% for such a purpose (https://github.com/oliver----/jsobjects)...
For now, I'd rather postpone integrating that and document how to get along with my helper lib.
Are you ok with that? 

Cheers,
oliver

**Comment by wsfulton** [comment]
@oliver---- happy to see you found some time to attend to this. Please join in the swig-devel mailing list conversation where we are discussing releasing 3.0 and possibly including javascript with it. Do you have the time/motivation to help and perhaps solicit the other folk interested in JavaScript to iron out the rough edges ready for merge to master? If not maybe one of the others can manage it all.

I havn't looked at the jsobjects library stand in for directors yet, but I don't see director support as being a prerequisite for merging into master though.

**Comment by obuchtala** [comment]
@wsfulton: yes I am motivated and will take the time it needs to make this happen :)

Of course, any collab is very welcome :)

Moving to #10 and closing this pull request.

**Pull request closed without merging**
